services:
  - type: web
    name: binance-signal-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    plan: free
    region: frankfurt
    branch: main
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
